#!/usr/bin/env bash
# 1-install_nginx_web_server
# a Bash script that configures a new Ubuntu machine
sudo apt-get update -y 
sudo apt-get install -y nginx
sudo ufw allow 80
sudo ufw enable
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx.html
sudo service nginx restart
