#!/usr/bin/env bash
sudo adduser --system --no-create-home --group nginx
sudo chown -R root:nginx /etc/nginx
sudo chmod -R 750 /etc/nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo service nginx restart
